### ISSUE TITLE
Trouble testing on Windows

### ISSUE THREAD

**Issue by git-nick-hub** [quan-dao/pmbm-filter#2]
I am having trouble building the wrapper on Windows 10.
I can run everything until "cmake .." but then I can't run "make" on Windows although I installed make using chocolatey. Do you have any workaround to make this work on Windows to get the .so file?
Also just to confirm, in the CMakeList.txt file, am I correct to understand that everything from the "find package" to and including "INCLUDE_DIRECTORIES" should be commented out?

**Comment by quan-dao** [comment]
Hello @git-nick-hub,
Unfortunately, I am not familiar with building C++ code on Window. 
A work around is to find a pure Python implementation of the Murty algorithm (e.g. https://gist.github.com/ryanpeach/738b560fd903857c061063d25b3c8225).
